a=math.sin(60)
print(a)
b=math.cos(pi)
print(b)
c=math.tan(90)
print(c)
print('The value of 5^8:'+ str(math.pow(5,8)))
x=math.sqrt(400)
print(x)
z=math.ceil(23.56)
print(z)
y=math.floor(23.56)
print(y)